fix optional param filtering
palantir/conjure-java pull request #28
Opened 2018-07-03 20:00 UTC by ferozco

Closes #27.

## Before this PR
There was an issue where the generated services would not compile if they had optional path params and body params

## After this PR

The issue is resolved and we preserve ordering of parameters

2018-07-03 21:06 UTC, markelliot requested changes

2018-07-03 21:06 UTC, markelliot commented on conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java
> +                    endpointDef,
If you don’t filter the params, you need to at least pass `i`, so that the method can filter the defaulted params...

2018-07-03 21:06 UTC, markelliot commented on conjure-java-core/src/test/resources/test/api/TestService.java.jersey
> +            Optional<ResourceIdentifier> optionalEnd,
this shouldn’t be an argument

2018-07-03 21:06 UTC, markelliot commented on conjure-java-core/src/test/resources/test/api/TestService.java.jersey
> +            Optional<ResourceIdentifier> optionalEnd,
shouldn’t be an argument

2018-07-03 23:41 UTC, markelliot approved these changes
Looks correct, now. Think it might be possible to make the code clearer/left some nits.

2018-07-03 23:41 UTC, markelliot commented on conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java
> +                .addParameters(IntStream.range(0, sortedParams.size())
Might be clearer to flatMap here?

2018-07-03 23:41 UTC, markelliot commented on conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java
> +        List<Optional<ArgumentDefinition>> sortedMaybeExtraArgs = sortedParams.stream().map(param ->
Wondering if it’d be better to change the method signature/this is a little gross and probably at least deserves a comment explaining what’s going on.

2018-07-03 23:41 UTC, markelliot commented on conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java
> +        List<Object> values = IntStream.range(0, sortedParams.size()).mapToObj(i -> {
Can maybe map over the sortedMaybeExtraArgs list?

2018-07-03 23:41 UTC, markelliot commented
Thanks for cleaning up my error.

2018-07-04 08:28 UTC, ferozco commented on conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java
> +                .addParameters(IntStream.range(0, sortedParams.size())
Unfortunately we can't since we need the index to check whether the arg exists in `sortedMaybeExtraArgs`

2018-07-04 12:22 UTC, iamdanfox approved these changes

2018-07-04 12:22 UTC, merged