[fix] nested aliased query params delegate to aliased type's valueOf static method
palantir/conjure-java pull request #77
Opened 2018-10-03 02:05 UTC by qinfchen

fixes https://github.com/palantir/conjure-java/issues/68
## Before this PR

Conjure generated endpoints with nested aliased query params do not meet any of the following conditions for `QueryParam` annotation type:
```
1. Be a primitive type
2. Have a constructor that accepts a single String argument
3. Have a static method named valueOf or fromString that accepts a single String argument (see, for example, Integer.valueOf(String))
4. Have a registered implementation of ParamConverterProvider JAX-RS extension SPI that returns a ParamConverter instance capable of a "from string" conversion for the type.
5. Be List<T>, Set<T> or SortedSet<T>, where T satisfies 2, 3 or 4 above. The resulting collection is read-only.
```
As a result, servers with those endpoints would fail with those exceptions
```
Caused by: org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed during application initialization.
[[FATAL] No injection source found for a parameter of type public com.palantir.product.AliasTwo com.palantir.conjure.java.EteResource.aliasTwo(com.palantir.tokens.auth.AuthHeader,com.palantir.product.AliasTwo) at index 1.; source='ResourceMethod{httpMethod=GET, consumedTypes=[application/json], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class com.palantir.conjure.java.EteResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@6ac4c3f7]}, definitionMethod=public abstract com.palantir.product.AliasTwo com.palantir.product.EteService.aliasTwo(com.palantir.tokens.auth.AuthHeader,com.palantir.product.AliasTwo), parameters=[Parameter [type=class com.palantir.tokens.auth.AuthHeader, source=Authorization, defaultValue=null], Parameter [type=class com.palantir.product.AliasTwo, source=queryParamName, defaultValue=null]], responseType=class com.palantir.product.AliasTwo}, nameBindings=[]}']
```

## After this PR

Nested aliased query params are now generated with a static method named valueOf that accepts string.

TODO:
- [ ] alias of `binary` and `any` type on query param never worked. Here is a [PR](https://github.com/palantir/conjure/pull/114) created in conjure-core to invalidate them at compile time instead of generation time

2018-10-03 03:47 UTC, uschi2000 commented
@nmiyake

2018-10-03 16:05 UTC, ferozco commented on conjure-java-core/src/main/java/com/palantir/conjure/java/types/AliasGenerator.java
> +            Optional<AliasDefinition> aliasTypeDef = typeMapper.getTypes().stream()
could we pull this out and construct map of typeNames to definitions?

2018-10-03 19:50 UTC, qinfchen commented on conjure-java-core/src/main/java/com/palantir/conjure/java/types/AliasGenerator.java
> +            Optional<AliasDefinition> aliasTypeDef = typeMapper.getTypes().stream()
Instead of return type definitions, we could just move the map to TypeMapper and have a getter for it if people are okay with that.

2018-10-12 15:03 UTC, dansanduleac approved these changes

2018-10-12 15:12 UTC, iamdanfox commented on conjure-java-core/src/main/java/com/palantir/conjure/java/types/AliasGenerator.java
> +            return aliasTypeDef.map(type -> {
I think there's a bug here because the following code-block assume that `type` is a conjure-defined type (because we got it from the `IS_REFERENCE` visitor).

HOWEVER - it seems the IS_REFERENCE visitor returns true for both external references and also internal references, so if it was actually pointing to an external class `Foo` then the `Foo.valueOf` method might not exist, leading to use generating broken code!

I think splitting the IS_REFERENCE visitor in two would be a reasonable way to solve this (it's bitten me in another project recently!)

2018-10-12 15:13 UTC, iamdanfox requested changes
Let's fix the external reference bug pls!  When this merges I think we should also follow-up to add this edge case to the central test-cases.yml so that all generators are forced to handle this https://github.com/palantir/conjure-verification/blob/develop/test-cases.yml

2018-10-15 11:58 UTC, iamdanfox approved these changes

2018-10-15 12:00 UTC, merged